#!/usr/bin/env node
/* <copyright>
Copyright (c) 2012, Motorola Mobility, Inc
All Rights Reserved.
BSD License.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

  - Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
  - Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
  - Neither the name of Motorola Mobility nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
</copyright> */

var fs = require("fs");
var path = require("path");

var args = process.argv.slice(3);
var options = {};
options.templateName = process.argv[2];

options.minitHome = __dirname + "/";
options.packageHome = ".";
while (true) {
    if (path.existsSync(path.join(options.packageHome, "package.json"))) {
        break;
    }
    options.packageHome = path.resolve(path.join(options.packageHome, ".."));
    if (options.packageHome === "/") {
        options.packageHome = __dirname;
        break;
    }
}

if (args.length === 0) {
    usage();
    process.exit();
}

var templatePath = path.join(options.minitHome, "templates", options.templateName);
var Template = require(templatePath).Template;
var templateStats = fs.statSync(templatePath);
if (templateStats.isDirectory()) {
    var aTemplate = Template.newWithNameAndOptions(templatePath, options);
    aTemplate.process(args);
} else {
    console.log("Invalid arguments.");
    console.log("Missing template directory: " + templatePath);
}

function usage() {
    console.log("Missing arguments.");
    var fileNames = fs.readdirSync(path.join(options.minitHome,"templates"));
    fileNames.forEach(function(filename) {
        var stats = fs.statSync(path.join(options.minitHome,"templates",filename));
        if (stats.isDirectory()) {
            console.log("Usage: minit " + filename + " " + require("./templates/" + filename).Template.usage());
        }
    });
}
