#!/usr/bin/env node
/* <copyright>
 This file contains proprietary software owned by Motorola Mobility, Inc.<br/>
 No rights, expressed or implied, whatsoever to this software are provided by Motorola Mobility, Inc. hereunder.<br/>
 (c) Copyright 2012 Motorola Mobility, Inc.  All Rights Reserved.
 </copyright> */
/*jshint node:true */

var fs = require("fs"),
    path = require("path"),
    JSHINT = require("./lib/jshint").JSHINT;
var linters = require("./linters"),
    linterNames = Object.keys(linters);

global.debug = false;

/**
    @function
    @param filenames {Array[String]} An array of filenames to lint
    @param [ignore] {Array[String]} An array of filenames to ignore, by default
                                    "node_modules" and "test" are ignored
    @param [problems] {Object} The object to insert the problems into
    @returns {Object} An object mapping filenames to an array of objects containing problems.
                      Each object has "problem", "line" and "solution" properties. e.g.
                      {"file.js": [{problem: "...", line: 1, solution: "..."}, ...], ...}
*/
var run = exports.run = function(filenames, ignore, problems) {
    ignore = ignore || ["node_modules", "test"];
    problems = problems || {};

    for (var i = 0, len = filenames.length; i < len; i++) {
        var filename = filenames[i],
            filePath = path.resolve(filename),
            basename = path.basename(filename);

        if (!path.existsSync(filename)) {
            if (global.debug){ console.error("Info: '" + filename + "' does not exist. Skipping."); }
            continue;
        }

        // Skip dotfiles.
        // fs.readdirSync doesn't include "." and ".." in its output, so if we
        // have them it's because the user passed them in explicitly. It's
        // likely they want to check the current or parent directory so don't
        // skip in that case.
        if (basename.indexOf(".") === 0 && basename !== "." && basename !== "..") {
            if (global.debug){ console.error("Info: " + filename + " is a dotfile. Skipping."); }
            continue;
        }
        if (ignore.indexOf(basename) !== -1) {
            if (global.debug){ console.error("Info: Ignoring " + filename); }
            continue;
        }

        // recurse into sub-directories
        if (fs.statSync(filename).isDirectory()) {
            var subProblems = run(fs.readdirSync(filename).map(function(f) {
                // prefix filename with the path
                return path.join(filename, f);
            }), ignore, problems);
            continue;
        }

        if (path.extname(filename) !== ".js") {
            if (global.debug){ console.error("Info: " + filename + " is not a JavaScript file. Skipping."); }
            continue;
        }

        problems[filename] = lint(filePath, fs.readFileSync(filePath, "utf8"));
    }

    return problems;
};

var lint = exports.lint = function(filePath, source) {
    JSHINT(source, {browser: true, node: true, trailing: true, strict: false});
    var jshint = JSHINT.data();
    // todo esprima

    var fileProblems = [];

    for (var i = 0, len = linterNames.length; i < len; i++) {
        var linter = linterNames[i];
        var linterProblems = linters[linter](filePath, source, jshint);
        if (linterProblems) {
            fileProblems = fileProblems.concat(linters[linter](filePath, source, jshint));
        }
    }
    return fileProblems;
};

function usage() {
    console.log("Usage: mint [ options ] filenames...");
    console.log();
    console.log("mint checks Montage Javascript files for coding errors.");
    console.log();
    console.log("\t--solution\tshow solutions along with problems");
    console.log("\t--ignore  \tcomma-separated list of filenames to ignore. Ignores node_modules and test by default");
    console.log("\t--debug   \tshow debug messages, such as skipped files");
}

if (!module.parent) {
    // this is the main module
    var args = process.argv.slice(2),
        solution = false,
        ignore = null;

    if (args.length === 0) {
        usage();
        process.exit();
    }

    var argPos = 0;
    if ((argPos = args.indexOf("--solution")) !== -1) {
        solution = true;
        args.splice(argPos, 1);
    }
    if ((argPos = args.indexOf("--debug")) !== -1) {
        global.debug = true;
        args.splice(argPos, 1);
    }
    if ((argPos = args.indexOf("--ignore")) !== -1) {
        ignore = args.splice(argPos, 2)[1].split(",");
    }

    var colors = require("./lib/termcolors").colors;
    var codeRe = /`([^`]+)`/g;

    var problems = run(args, ignore);
    for (var filename in problems) {
        for (var i = 0, len = problems[filename].length; i < len; i++) {
            var p = problems[filename][i];
            console.log(colors.brown(filename + ":" + p.line, true) + " " + p.problem);
            if (solution) {

                console.log(colors.green("> ", true) + p.solution.replace(codeRe, "`" + colors.dgray("$1", true) + "`" ));
            }
        }
    }
}